### ISSUE TITLE
why tf use emails

### ISSUE THREAD

**Issue by dropsql** [fortysev-en/chrome_pwd_extractor_email#1]
you should use an REST api (on a vps / telegram bot / discord web hook) instead of using your own email lmfao.

**Comment by fortysev-en** [comment]
Hi, I understand, I've just made this version for people who don't understand much about APIs and YES, I do have another version where I've used Google's FIrebase Realtime DB along with tons of other functionalities. It's a private repo ATM, I'll make it public in a few days.

**Comment by dropsql** [comment]
okay nice
